[package]
name = "mini-sqldb-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "2.0", features = ["serde"] }
fs4 = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
strum = "0.27.1"
strum_macros = "0.27.1"
tempfile = "3.19"
